-- 1) Tabela benefits (cria se não existir)
CREATE TABLE IF NOT EXISTS aviv.benefits (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(180) NOT NULL,
  partner VARCHAR(120) DEFAULT NULL,
  `type` VARCHAR(50) DEFAULT NULL,
  image_url VARCHAR(255) DEFAULT NULL,
  description TEXT NULL,
  url VARCHAR(255) DEFAULT NULL,
  discount VARCHAR(50) DEFAULT NULL,
  terms TEXT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2) Adiciona colunas que porventura faltem (uma a uma)
-- partner
SET @c=(SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA='aviv' AND TABLE_NAME='benefits' AND COLUMN_NAME='partner');
SET @sql=IF(@c=0,'ALTER TABLE aviv.benefits ADD COLUMN partner VARCHAR(120) DEFAULT NULL','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- type (palavra protegida em algumas libs: use crase)
SET @c=(SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA='aviv' AND TABLE_NAME='benefits' AND COLUMN_NAME='type');
SET @sql=IF(@c=0,'ALTER TABLE aviv.benefits ADD COLUMN `type` VARCHAR(50) DEFAULT NULL','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- image_url
SET @c=(SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA='aviv' AND TABLE_NAME='benefits' AND COLUMN_NAME='image_url');
SET @sql=IF(@c=0,'ALTER TABLE aviv.benefits ADD COLUMN image_url VARCHAR(255) DEFAULT NULL','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- description
SET @c=(SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA='aviv' AND TABLE_NAME='benefits' AND COLUMN_NAME='description');
SET @sql=IF(@c=0,'ALTER TABLE aviv.benefits ADD COLUMN description TEXT NULL','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- url
SET @c=(SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA='aviv' AND TABLE_NAME='benefits' AND COLUMN_NAME='url');
SET @sql=IF(@c=0,'ALTER TABLE aviv.benefits ADD COLUMN url VARCHAR(255) DEFAULT NULL','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- discount
SET @c=(SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA='aviv' AND TABLE_NAME='benefits' AND COLUMN_NAME='discount');
SET @sql=IF(@c=0,'ALTER TABLE aviv.benefits ADD COLUMN discount VARCHAR(50) DEFAULT NULL','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- terms
SET @c=(SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA='aviv' AND TABLE_NAME='benefits' AND COLUMN_NAME='terms');
SET @sql=IF(@c=0,'ALTER TABLE aviv.benefits ADD COLUMN terms TEXT NULL','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- is_active
SET @c=(SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA='aviv' AND TABLE_NAME='benefits' AND COLUMN_NAME='is_active');
SET @sql=IF(@c=0,'ALTER TABLE aviv.benefits ADD COLUMN is_active TINYINT(1) NOT NULL DEFAULT 1','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- created_at
SET @c=(SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA='aviv' AND TABLE_NAME='benefits' AND COLUMN_NAME='created_at');
SET @sql=IF(@c=0,'ALTER TABLE aviv.benefits ADD COLUMN created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- updated_at
SET @c=(SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA='aviv' AND TABLE_NAME='benefits' AND COLUMN_NAME='updated_at');
SET @sql=IF(@c=0,'ALTER TABLE aviv.benefits ADD COLUMN updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- 3) Tabela de vínculo plano x benefício
CREATE TABLE IF NOT EXISTS aviv.benefit_plans (
  benefit_id INT NOT NULL,
  plan_id VARCHAR(50) NOT NULL,
  PRIMARY KEY (benefit_id, plan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
